#!/usr/bin/env bash
#
# gen-secrets.sh — generate a COMPLETE, coordinated secret set for a Bud Foundry install.
#
# Writes matching values into the bud chart secrets AND the stateful addon
# configs. The addons (postgres/clickhouse/kafka/mongodb/valkey/seaweedfs) CREATE
# their users from their own values; the bud chart CONNECTS with the same
# passwords. A mismatch = pods that can't connect. This keeps them in sync.
#
# The bud key set is anchored to the chart's own example.secrets.yaml at the
# pinned version, and the script renders the chart at the end to PROVE the
# generated file is complete (catches drift when the chart adds keys).
#
# Outputs (gitignored in the PUBLIC example; you MUST git add -f them in your
# PRIVATE fork — ArgoCD delivers config via git, see the note printed at the end):
#   argocd/bud/secrets.yaml
#   argocd/{postgres,clickhouse,kafka,mongodb,valkey,seaweedfs}/secrets.yaml
#
# Registry creds + external API keys (HF_TOKEN, OPENAI_API_KEY) are NOT generated.
#
# Usage:
#   scripts/gen-secrets.sh --registry-user 'robot$you' --registry-token '<tok>' \
#     [--admin-email you@co.com] [--hf-token <tok>] [--openai-key <key>] \
#     [--chart-version 0.14.0] [--no-verify] [--force]
#
# Requires: bash, openssl. (helm is OPTIONAL — only used for the completeness
# render-test, which is skipped when helm isn't installed.)

set -euo pipefail

REGISTRY_USER="" REGISTRY_TOKEN="" ADMIN_EMAIL="admin@example.com"
HF_TOKEN="<change_me>" OPENAI_KEY="<change_me>"
CHART_VERSION="0.14.0" VERIFY=1 FORCE=0
REGISTRY="registry.bud.studio"

usage() { sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }
while [ $# -gt 0 ]; do
  case "$1" in
    --registry-user)  REGISTRY_USER="${2:-}"; shift 2 ;;
    --registry-token) REGISTRY_TOKEN="${2:-}"; shift 2 ;;
    --admin-email)    ADMIN_EMAIL="${2:-}"; shift 2 ;;
    --hf-token)       HF_TOKEN="${2:-}"; shift 2 ;;
    --openai-key)     OPENAI_KEY="${2:-}"; shift 2 ;;
    --chart-version)  CHART_VERSION="${2:-}"; shift 2 ;;
    --no-verify)      VERIFY=0; shift ;;
    --force)          FORCE=1; shift ;;
    -h|--help)        usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done
[ -n "$REGISTRY_USER" ] && [ -n "$REGISTRY_TOKEN" ] || {
  echo "ERROR: --registry-user and --registry-token are required (issued by Bud)." >&2; usage 1; }

ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"

# ---- generators (SIGPIPE-safe; no `</dev/urandom | head`) --------------------
gen() { local n="${1:-32}"; LC_ALL=C openssl rand -base64 $((n*2+16)) | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c "1-${n}"; }
gen_hex() { openssl rand -hex "${1:-44}"; }   # AES_KEY_HEX: 88 hex chars per chart example

# ---- coordinated values -----------------------------------------------------
PG_BUD_PW="$(gen)"; PG_KEYCLOAK_PW="$(gen)"; PG_SEAWEEDFS_PW="$(gen)"
CH_PW="$(gen)"; KAFKA_PW="$(gen)"; MONGO_PW="$(gen)"; VALKEY_PW="$(gen)"
KEYCLOAK_ADMIN_PW="$(gen)"
NOVU_ENCRYPTION_KEY="bud-$(gen 28)"; NOVU_EXTRA_PW="$(gen 24)"
APP_API_TOKEN="$(gen)"; PASSWORD_SALT="$(gen 64)"; AES_KEY_HEX="$(gen_hex 44)"
SUPER_USER_PASSWORD="$(gen)"
S3_SECRET_KEY="$(gen)"
BUDAPP_JWT="$(gen 64)"; GRAFANA_PW="$(gen)"
SESSION_SECRET="$(gen 64)"; DEFAULT_CLIENT_SECRET="$(gen)"
BUDADMIN_CS="$(gen)"; BUDCUSTOMER_CS="$(gen)"; BUDPLAYGROUND_CS="$(gen)"
BUDNOTIFY_STORE_KEY="$(gen)"; BUDNOTIFY_JWT="$(gen 64)"
MCP_BASIC_PW="$(gen 24)"; MCP_JWT="$(gen)"; MCP_ADMIN_PW="$(gen 24)"; MCP_AUTH_ENC="$(gen)"
MCPGATEWAY_OIDC_SECRET="$(gen)"  # the mcpgateway OAuth client secret; bud-side AND keycloak realm must match
DAPR_SYM_KEY="$(gen)"

RSA_PW="$(gen)"
RSA_PRIV="$(openssl genrsa -aes256 -passout "pass:${RSA_PW}" 2048 2>/dev/null)"
printf '%s\n' "$RSA_PRIV" > "/tmp/.budrsa.$$"
RSA_PUB="$(openssl rsa -in "/tmp/.budrsa.$$" -passin "pass:${RSA_PW}" -pubout 2>/dev/null)"
DAPR_ASYM="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 2>/dev/null)"
rm -f "/tmp/.budrsa.$$"
indent6() { printf '%s\n' "$1" | sed 's/^/      /'; }

# ---- overwrite guard --------------------------------------------------------
OUTPUTS=(argocd/bud/secrets.yaml argocd/postgres/secrets.yaml argocd/clickhouse/secrets.yaml
  argocd/kafka/secrets.yaml argocd/mongodb/secrets.yaml argocd/valkey/secrets.yaml
  argocd/seaweedfs/secrets.yaml argocd/keycloak/secrets.yaml)
if [ "$FORCE" -ne 1 ]; then
  for f in "${OUTPUTS[@]}"; do
    [ -e "$f" ] && { echo "ERROR: $f exists. Re-run with --force to regenerate ALL secrets." >&2; exit 1; }
  done
fi
mkdir -p argocd/bud argocd/postgres argocd/clickhouse argocd/kafka argocd/mongodb argocd/valkey argocd/seaweedfs argocd/keycloak

# ---- bud/secrets.yaml (complete, anchored to chart example.secrets.yaml) ----
cat > argocd/bud/secrets.yaml <<EOF
# GENERATED by scripts/gen-secrets.sh — DO NOT commit to a public repo.
# Coordinated with argocd/<addon>/secrets.yaml. Re-run with --force to regenerate
# everything together; never hand-edit one file in isolation.
registries:
  ${REGISTRY}:
    username: "${REGISTRY_USER}"
    password: "${REGISTRY_TOKEN}"
appApiToken: "${APP_API_TOKEN}"
externalServices:
  s3:
    auth: { accessKey: bud, secretKey: "${S3_SECRET_KEY}" }
  mongodb:
    # username MUST match the chart default + the addon user (bud_novu). The chart's
    # example.secrets.yaml says bud_novu_mongodb but values.yaml uses bud_novu — the
    # latter is authoritative (novu connects as bud_novu).
    auth: { username: bud_novu, password: "${MONGO_PW}" }
  valkey:
    password: "${VALKEY_PW}"
  clickhouse:
    auth: { username: bud, password: "${CH_PW}" }
  kafka:
    auth: { username: bud, password: "${KAFKA_PW}" }
  postgresql:
    databases:
      keycloak: { username: keycloak, password: "${PG_KEYCLOAK_PW}" }
      budask: { username: bud, password: "${PG_BUD_PW}" }
      budapp: { username: bud, password: "${PG_BUD_PW}" }
      budcluster: { username: bud, password: "${PG_BUD_PW}" }
      budmetrics: { username: bud, password: "${PG_BUD_PW}" }
      budmodel: { username: bud, password: "${PG_BUD_PW}" }
      budsim: { username: bud, password: "${PG_BUD_PW}" }
      budeval: { username: bud, password: "${PG_BUD_PW}" }
      buddoc: { username: bud, password: "${PG_BUD_PW}" }
      budprompt: { username: bud, password: "${PG_BUD_PW}" }
      mcpgateway: { username: bud, password: "${PG_BUD_PW}" }
      budpipeline: { username: bud, password: "${PG_BUD_PW}" }
      onyx: { username: bud, password: "${PG_BUD_PW}" }
  # mcpgateway OAuth client — secret MUST equal the keycloak realm's mcpgateway
  # client (argocd/keycloak/secrets.yaml). id defaults to "mcpgateway" in the chart.
  oidc:
    clients:
      mcpgateway:
        secret: "${MCPGATEWAY_OIDC_SECRET}"
novu:
  externalDatabase:
    username: bud_novu
    password: "${MONGO_PW}"
  store:
    encryption-key: "${NOVU_ENCRYPTION_KEY}"
novuExtra:
  email: "${ADMIN_EMAIL}"
  password: "${NOVU_EXTRA_PW}"
microservices:
  rsaKeys:
    privateKeyPassword: "${RSA_PW}"
    privateKey: |
$(indent6 "$RSA_PRIV")
    publicKey: |
$(indent6 "$RSA_PUB")
  budapp:
    env:
      JWT_SECRET_KEY: "${BUDAPP_JWT}"
      HF_TOKEN: "${HF_TOKEN}"
      GRAFANA_USERNAME: bud-runtime
      GRAFANA_PASSWORD: "${GRAFANA_PW}"
      AES_KEY_HEX: "${AES_KEY_HEX}"
    redirectFlow:
      sessionSecret: "${SESSION_SECRET}"
      defaultClientId: budadmin-web
      defaultClientSecret: "${DEFAULT_CLIENT_SECRET}"
      # App-keyed override (matches the chart's default clientsByHost keys), so
      # Helm overwrites in place instead of ADDING host-keyed entries (which would
      # duplicate the client_id and make budapp skip the redirect-flow router ->
      # /auth/redirect/* 404). Only clientSecret is set; clientId + hosts come from
      # the chart. The chart's example.secrets.yaml uses the host-keyed form — DON'T;
      # values.yaml is authoritative and defines these app keys.
      clientsByHost:
        budadmin:
          clientSecret: "${BUDADMIN_CS}"
        budcustomer:
          clientSecret: "${BUDCUSTOMER_CS}"
        budplayground:
          clientSecret: "${BUDPLAYGROUND_CS}"
  budnotify:
    env:
      STORE_ENCRYPTION_KEY: "${BUDNOTIFY_STORE_KEY}"
      JWT_SECRET: "${BUDNOTIFY_JWT}"
  mcpgateway:
    env:
      BASIC_AUTH_USER: root
      BASIC_AUTH_PASSWORD: "${MCP_BASIC_PW}"
      JWT_SECRET_KEY: "${MCP_JWT}"
      PLATFORM_ADMIN_EMAIL: "${ADMIN_EMAIL}"
      PLATFORM_ADMIN_PASSWORD: "${MCP_ADMIN_PW}"
      AUTH_ENCRYPTION_SECRET: "${MCP_AUTH_ENC}"
  global:
    env:
      OPENAI_API_KEY: "${OPENAI_KEY}"
      PASSWORD_SALT: "${PASSWORD_SALT}"
      SUPER_USER_EMAIL: "${ADMIN_EMAIL}"
      SUPER_USER_PASSWORD: "${SUPER_USER_PASSWORD}"
keycloak:
  auth:
    adminUser: user
    adminPassword: "${KEYCLOAK_ADMIN_PW}"
daprExtra:
  crypto:
    symmetricKey: "${DAPR_SYM_KEY}"
    asymmetricKey: |
$(indent6 "$DAPR_ASYM")
EOF

# ---- addon secrets: the user/db/role/grant STRUCTURE is non-secret and stable
#      per chart version; it's embedded below (verified against each addon's
#      values.budruntime.yaml at chart 0.1.0). Only the passwords are generated.
#      This keeps the script openssl-only — no helm/yq needed on the deploy host.
#      If you bump the addon chart versions, re-verify these blocks.

# postgres: 'bud' owns all bud_* DBs; keycloak + seaweedfs own their own.
cat > argocd/postgres/secrets.yaml <<EOF
# GENERATED — structure matches the postgres chart's authoritative users block.
users:
  seaweedfs:
    password: "${PG_SEAWEEDFS_PW}"
    databases:
      - seaweedfs
  keycloak:
    password: "${PG_KEYCLOAK_PW}"
    databases:
      - keycloak
  bud:
    password: "${PG_BUD_PW}"
    databases:
      - keycloak2
      - budask
      - budapp
      - budcluster
      - budmetrics
      - budmodel
      - budsim
      - budeval
      - buddoc
      - budprompt
      - budcodeinterpreter
      - mcpgateway
      - budpipeline
      - onyx
EOF

# clickhouse: 'bud' user with its databases + grants (metrics is Replicated).
cat > argocd/clickhouse/secrets.yaml <<EOF
# GENERATED — structure matches the clickhouse chart's authoritative users block.
users:
  bud:
    password: "${CH_PW}"
    databases:
      - name: bud_eval
      - name: bud_gateway
      - name: metrics
        extraArgs: "ENGINE = Replicated('/clickhouse/databases/{{ . }}', '{shard}', '{replica}')"
    grants:
      - ALL ON metrics.*
      - SELECT(path) ON system.zookeeper
      - SELECT(cluster, replica_num) ON system.clusters
      - SELECT(macro, substitution) ON system.macros
EOF

# kafka: 'bud' user.
cat > argocd/kafka/secrets.yaml <<EOF
# GENERATED — structure matches the kafka chart's authoritative users block.
users:
  bud:
    password: "${KAFKA_PW}"
    spec: {}
EOF

# mongodb: 'bud_novu' user with db + dbOwner role (this is what novu connects as).
cat > argocd/mongodb/secrets.yaml <<EOF
# GENERATED — structure matches the mongodb chart's authoritative users block.
users:
  bud_novu:
    db: bud_novu
    password: "${MONGO_PW}"
    roles:
      - name: dbOwner
        db: bud_novu
EOF

# valkey: auth.password (sticky-secret subchart — see README note on first-deploy)
cat > argocd/valkey/secrets.yaml <<EOF
# GENERATED — matches argocd/bud/secrets.yaml externalServices.valkey
valkey:
  auth:
    password: "${VALKEY_PW}"
EOF

# seaweedfs: connects to its own in-cluster Postgres user (matches postgres users.seaweedfs)
cat > argocd/seaweedfs/secrets.yaml <<EOF
# GENERATED — seaweedfs connects to its own in-cluster Postgres user;
# password matches the 'seaweedfs' user in argocd/postgres/secrets.yaml.
postgres:
  host: "pooler-rw.postgres"
  port: 5432
  username: "seaweedfs"
  password: "${PG_SEAWEEDFS_PW}"
  database: "seaweedfs"
EOF

# keycloak: DB password (matches the postgres addon's 'keycloak' user), admin
# password, the super-user, and the realm OAuth clients whose secrets MUST equal
# bud's redirectFlow / oidc client secrets (else budapp login -> invalid_client).
# realm STRUCTURE (realm name, redirect URIs) lives in keycloak/values.yaml.
cat > argocd/keycloak/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml and the postgres addon.
postgres:
  password: "${PG_KEYCLOAK_PW}"
password: "${KEYCLOAK_ADMIN_PW}" # keycloak admin (matches bud keycloak.auth.adminPassword)
realmImport:
  users:
    - username: "${ADMIN_EMAIL}"
      email: "${ADMIN_EMAIL}" # MUST equal bud SUPER_USER_EMAIL
      password: "${SUPER_USER_PASSWORD}" # MUST equal bud SUPER_USER_PASSWORD
      realmRoles: [super_admin]
  clients:
    budadmin:
      clientId: budadmin-web
      clientSecret: "${BUDADMIN_CS}"
    budcustomer:
      clientId: budcustomer-web
      clientSecret: "${BUDCUSTOMER_CS}"
    budplayground:
      clientId: budplayground-web
      clientSecret: "${BUDPLAYGROUND_CS}"
    mcpgateway:
      clientId: mcpgateway
      clientSecret: "${MCPGATEWAY_OIDC_SECRET}"
EOF

# ---- completeness self-test: render the real chart with the generated file --
if [ "$VERIFY" -eq 1 ]; then
  if command -v helm >/dev/null 2>&1; then
    echo "🔍 Verifying generated secrets render the bud chart cleanly…"
    TMP="$(mktemp -d)"
    if helm pull "oci://${REGISTRY}/charts/bud" --version "$CHART_VERSION" --untar --untardir "$TMP" >/dev/null 2>&1; then
      printf 'global:\n  ingress:\n    hosts:\n      root: "verify.example.com"\n' > "$TMP/v.yaml"
      if helm template bud "$TMP/bud" -f "$TMP/v.yaml" -f argocd/bud/secrets.yaml >/dev/null 2>"$TMP/err"; then
        echo "✅ Render check passed — bud/secrets.yaml is complete for chart $CHART_VERSION."
      else
        echo "❌ Render check FAILED — bud/secrets.yaml is missing a key the chart needs:" >&2
        grep -iE "at <|Error:" "$TMP/err" | head -3 >&2
        echo "   (chart $CHART_VERSION may have added keys; update this script against its example.secrets.yaml)" >&2
        rm -rf "$TMP"; exit 1
      fi
    else
      echo "⚠️  Could not pull chart to verify (registry login?). Skipping render check." >&2
    fi
    rm -rf "$TMP"
  else
    echo "⚠️  helm not found — skipping render check. Install helm or pass --no-verify knowingly." >&2
  fi
fi

echo ""
echo "✅ Generated coordinated secrets:"
for f in "${OUTPUTS[@]}"; do echo "   $f"; done
cat <<EOF

⚠️  DELIVERY — ArgoCD reads config from GIT, and these files are gitignored.
   In YOUR PRIVATE fork you MUST force-add and push them, or ArgoCD renders
   with values.yaml only and the bud Application fails with a nil-pointer:

     git add -f ${OUTPUTS[*]}
     git commit -m "add generated secrets" && git push

   Keep the fork PRIVATE. After pushing, HARD-REFRESH the ArgoCD apps
   (the manifest error is cached).

   Admin login: ${ADMIN_EMAIL} / SUPER_USER_PASSWORD (in argocd/bud/secrets.yaml)
   Set by hand if you use them: HF_TOKEN / OPENAI_API_KEY.
EOF
