#!/usr/bin/env bash
#
# gen-secrets.sh — generate a coordinated set of secrets for a Bud Foundry install.
#
# Writes matching passwords into BOTH the bud chart's secrets file AND the
# stateful addon configs, because the databases run in-cluster: the postgres /
# clickhouse / kafka / mongodb / valkey addons CREATE their users from their own
# values, and the bud chart CONNECTS using the same passwords. A mismatch =
# backend pods that can't connect. This script keeps them in sync from one run.
#
# Outputs (all gitignored / .secret.yaml so they never reach a public repo):
#   argocd/bud/secrets.yaml
#   argocd/postgres/secrets.yaml
#   argocd/clickhouse/secrets.yaml
#   argocd/kafka/secrets.yaml
#   argocd/mongodb/secrets.yaml
#   argocd/valkey/secrets.yaml
#
# Registry credentials are ISSUED by Bud, not generated — pass them in.
#
# Usage:
#   scripts/gen-secrets.sh \
#     --registry-user 'robot$yourname' \
#     --registry-token '<token>' \
#     [--admin-email admin@yourco.com] \
#     [--force]
#
# Requires: bash, openssl. (tr/sed/awk from coreutils.)

set -euo pipefail

# ---- args -------------------------------------------------------------------
REGISTRY_USER=""
REGISTRY_TOKEN=""
ADMIN_EMAIL="admin@example.com"
FORCE=0

usage() { sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --registry-user)  REGISTRY_USER="${2:-}"; shift 2 ;;
    --registry-token) REGISTRY_TOKEN="${2:-}"; shift 2 ;;
    --admin-email)    ADMIN_EMAIL="${2:-}"; shift 2 ;;
    --force)          FORCE=1; shift ;;
    -h|--help)        usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

if [ -z "$REGISTRY_USER" ] || [ -z "$REGISTRY_TOKEN" ]; then
  echo "ERROR: --registry-user and --registry-token are required (issued by Bud, not generated)." >&2
  usage 1
fi

# Run from the repo root regardless of where it's invoked.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# ---- generators -------------------------------------------------------------
# Alphanumeric secret (default 32 chars). Built from openssl base64 (not
# `tr </dev/urandom | head`, which triggers SIGPIPE under `set -o pipefail`).
gen() {
  local n="${1:-32}"
  # base64 of plenty of bytes, strip non-alnum, take n chars.
  LC_ALL=C openssl rand -base64 $(( n * 2 + 16 )) | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c "1-${n}"
}
# Hex of N bytes (AES_KEY_HEX wants 48 bytes = 96 hex chars; matches chart default).
gen_hex() { openssl rand -hex "${1:-48}"; }

# One coordinated password per data store (shared across the files that need it).
PG_BUD_PW="$(gen)"          # the shared 'bud' postgres role (owns all bud_* DBs)
PG_KEYCLOAK_PW="$(gen)"     # keycloak's own postgres role + DB
CH_BUD_PW="$(gen)"          # clickhouse 'bud' user
KAFKA_BUD_PW="$(gen)"       # kafka 'bud' user
MONGO_BUD_PW="$(gen)"       # mongodb 'bud' user
VALKEY_PW="$(gen)"          # valkey requirepass

APP_API_TOKEN="$(gen)"
PASSWORD_SALT="$(gen)"
AES_KEY_HEX="$(gen_hex 48)"
SUPER_USER_PASSWORD="$(gen)"
S3_ACCESS_KEY="$(gen 20)"
S3_SECRET_KEY="$(gen 40)"
MCPGATEWAY_OIDC_SECRET="$(gen)"
RSA_KEY_PASSWORD="$(gen)"

# Encrypted RSA private key (PEM). Indented 6 spaces to sit under a `|` block
# scalar at `microservices.rsaKeys.privateKey`.
RSA_PEM="$(openssl genrsa -aes256 -passout "pass:${RSA_KEY_PASSWORD}" 2048 2>/dev/null)"
RSA_PEM_INDENTED="$(printf '%s\n' "$RSA_PEM" | sed 's/^/      /')"

# ---- overwrite guard --------------------------------------------------------
OUTPUTS=(
  argocd/bud/secrets.yaml
  argocd/postgres/secrets.yaml
  argocd/clickhouse/secrets.yaml
  argocd/kafka/secrets.yaml
  argocd/mongodb/secrets.yaml
  argocd/valkey/secrets.yaml
)
if [ "$FORCE" -ne 1 ]; then
  for f in "${OUTPUTS[@]}"; do
    if [ -e "$f" ]; then
      echo "ERROR: $f already exists. Re-run with --force to overwrite (this regenerates ALL secrets)." >&2
      exit 1
    fi
  done
fi

mkdir -p argocd/bud argocd/postgres argocd/clickhouse argocd/kafka argocd/mongodb argocd/valkey

# ---- bud/secrets.yaml (the chart connects with these) -----------------------
cat > argocd/bud/secrets.yaml <<EOF
# GENERATED by scripts/gen-secrets.sh — DO NOT commit to a public repo.
# Passwords here are coordinated with argocd/<addon>/secrets.yaml. Re-running the
# script regenerates ALL of them together; never edit one file in isolation.
registries:
  registry.bud.studio:
    username: "${REGISTRY_USER}"
    password: "${REGISTRY_TOKEN}"

appApiToken: "${APP_API_TOKEN}"

microservices:
  rsaKeys:
    privateKeyPassword: "${RSA_KEY_PASSWORD}"
    privateKey: |
${RSA_PEM_INDENTED}
  global:
    env:
      SUPER_USER_EMAIL: "${ADMIN_EMAIL}"
      SUPER_USER_PASSWORD: "${SUPER_USER_PASSWORD}"
      PASSWORD_SALT: "${PASSWORD_SALT}"
  budapp:
    env:
      AES_KEY_HEX: "${AES_KEY_HEX}"

externalServices:
  postgresql:
    databases:
      keycloak:   { username: keycloak, password: "${PG_KEYCLOAK_PW}" }
      budapp:     { username: bud, password: "${PG_BUD_PW}" }
      budcluster: { username: bud, password: "${PG_BUD_PW}" }
      budmetrics: { username: bud, password: "${PG_BUD_PW}" }
      budmodel:   { username: bud, password: "${PG_BUD_PW}" }
      budsim:     { username: bud, password: "${PG_BUD_PW}" }
      budeval:    { username: bud, password: "${PG_BUD_PW}" }
      budask:     { username: bud, password: "${PG_BUD_PW}" }
  clickhouse:
    auth: { username: bud, password: "${CH_BUD_PW}" }
  kafka:
    auth: { username: bud, password: "${KAFKA_BUD_PW}" }
  mongodb:
    auth: { username: bud, password: "${MONGO_BUD_PW}" }
  valkey:
    password: "${VALKEY_PW}"
  s3:
    auth: { accessKey: "${S3_ACCESS_KEY}", secretKey: "${S3_SECRET_KEY}" }
  oidc:
    clients:
      mcpgateway: { secret: "${MCPGATEWAY_OIDC_SECRET}" }
  keycloak:
    clients:
      mcpgateway: { secret: "${MCPGATEWAY_OIDC_SECRET}" }
EOF

# ---- postgres addon (CREATES the users + DBs) -------------------------------
# The shared 'bud' role owns every bud_* database; keycloak owns its own.
cat > argocd/postgres/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml (externalServices.postgresql).
users:
  bud:
    password: "${PG_BUD_PW}"
    databases:
      - budapp
      - budcluster
      - budmetrics
      - budmodel
      - budsim
      - budeval
      - budask
  keycloak:
    password: "${PG_KEYCLOAK_PW}"
    databases:
      - keycloak
EOF

# ---- clickhouse addon -------------------------------------------------------
cat > argocd/clickhouse/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml (externalServices.clickhouse).
users:
  bud:
    password: "${CH_BUD_PW}"
EOF

# ---- kafka addon ------------------------------------------------------------
cat > argocd/kafka/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml (externalServices.kafka).
users:
  bud:
    password: "${KAFKA_BUD_PW}"
EOF

# ---- mongodb addon ----------------------------------------------------------
cat > argocd/mongodb/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml (externalServices.mongodb).
users:
  bud:
    password: "${MONGO_BUD_PW}"
EOF

# ---- valkey addon -----------------------------------------------------------
cat > argocd/valkey/secrets.yaml <<EOF
# GENERATED — coordinated with argocd/bud/secrets.yaml (externalServices.valkey).
valkey:
  auth:
    password: "${VALKEY_PW}"
EOF

echo "✅ Generated coordinated secrets:"
for f in "${OUTPUTS[@]}"; do echo "   $f"; done
cat <<EOF

Next:
  • Wire each addon's secrets.yaml into cluster-addons.yaml so it is applied
    (add a "secrets://\$values/argocd/<addon>/secrets.yaml" or
    "\$values/argocd/<addon>/secrets.yaml" valueFile to that addon).
  • Commit these to a PRIVATE repo, or encrypt with SOPS + the helm-secrets
    ArgoCD plugin. NEVER commit them to a public repo.
  • Admin login: ${ADMIN_EMAIL} / (generated SUPER_USER_PASSWORD in bud/secrets.yaml)
EOF
